const fields=['나라','성별','재산','가정 환경','재능'];
const state={active:0,round:1,results:Array(5).fill(null),pools:Array.from({length:5},()=>new Map()),connecting:false,collecting:false,until:0,rolling:false,streamerName:'',status:'방송 주소를 입력한 뒤 수집을 시작하세요.'};
const $=id=>document.getElementById(id);let controller,drawTimer,reelFrame,toastTimer,generation=0;
const isOverlay=new URLSearchParams(location.search).has('overlay'),syncKey='rebirth-roulette-live-v1',syncChannel='BroadcastChannel' in window?new BroadcastChannel(syncKey):null;
if(isOverlay)document.body.classList.add('overlay');
function snapshot(){return {active:state.active,round:state.round,results:state.results,pools:state.pools.map(pool=>[...pool.values()]),connecting:state.connecting,collecting:state.collecting,until:state.until,rolling:state.rolling,streamerName:state.streamerName,status:state.status}}
function publish(){if(isOverlay)return;const data=JSON.stringify(snapshot());try{localStorage.setItem(syncKey,data)}catch{}syncChannel?.postMessage(data)}
function applySnapshot(data){if(!isOverlay)return;try{const next=typeof data==='string'?JSON.parse(data):data;if(!next||!Array.isArray(next.pools))return;Object.assign(state,next,{pools:next.pools.map(list=>new Map(list.map(item=>[item.id,item])))});render()}catch{}}
const sample=[['대한민국','아이슬란드','달나라','고양이 왕국'],['여성','남성','성별 없는 정령'],['통장 잔고 500원','건물 세 채','빚 10억'],['화목한 대가족','왕실의 막내','고양이에게 입양됨'],['순간이동','절대음감','모든 동물과 대화']];
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',3000)}
function add(id,name,text){if(!state.collecting||Date.now()>=state.until||state.rolling)return;text=String(text).replace(/[\x00-\x1f]/g,' ').trim();id=String(id||'').trim();if(!id||!text||[...text].length>80)return;const pool=state.pools[state.active];if(pool.size>=2000&&!pool.has(id))return;pool.set(id,{id,name:String(name||'시청자').slice(0,40),text});render()}
async function startCollection(){
 if(state.connecting||state.collecting||state.rolling)return;
 const streamer=$('streamer').value.trim();if(!streamer)return toast('SOOP 방송국 ID나 라이브 주소를 입력하세요.');
 const token=++generation;controller=new AbortController();state.pools[state.active].clear();state.results[state.active]=null;state.connecting=true;state.status='Vercel 수집 함수를 시작하는 중…';render();
 try{
  const response=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({streamer}),signal:controller.signal});
  if(!response.ok){let message='수집 요청에 실패했습니다.';try{message=(await response.json()).error||message}catch{}throw Error(message)}
  if(!response.body)throw Error('스트리밍 응답을 받을 수 없습니다.');
  const reader=response.body.pipeThrough(new TextDecoderStream()).getReader();let buffer='';
  while(true){const {value,done}=await reader.read();if(done)break;if(token!==generation){reader.cancel();break}buffer+=value;let end;
   while((end=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,end).trim();buffer=buffer.slice(end+1);if(!line)continue;let event;try{event=JSON.parse(line)}catch{continue}
    if(event.type==='status')state.status=event.message;
    if(event.type==='entered'){state.connecting=false;state.collecting=true;state.until=Date.now()+Number(event.duration||30)*1000;state.streamerName=event.streamerName||event.streamer||'';state.status=event.message;}
    if(event.type==='chat')add(event.id,event.name,event.text);
    if(event.type==='done'){state.connecting=false;state.collecting=false;state.until=0;state.status=event.message;}
    if(event.type==='error')throw Error(event.message);
    render();
   }
  }
 }catch(error){if(token!==generation||error.name==='AbortError')return;state.status=error.message;toast(error.message);}
 finally{if(token===generation){state.connecting=false;state.collecting=false;state.until=0;controller=null;render();}}
}
function cancelCollection(){generation++;controller?.abort();controller=null;state.connecting=false;state.collecting=false;state.until=0;}
function reset(all=true){cancelCollection();clearTimeout(drawTimer);cancelAnimationFrame(reelFrame);Object.assign(state,{active:0,round:all?1:state.round+1,results:Array(5).fill(null),pools:Array.from({length:5},()=>new Map()),rolling:false,status:'초기화 완료 · 방송 주소는 유지됩니다.'});$('reelTrack').style.transform='';render()}
function random(pool){const max=0x100000000-(0x100000000%pool.length);let n;do n=crypto.getRandomValues(new Uint32Array(1))[0];while(n>=max);return pool[n%pool.length]}
function draw(reroll=false){const index=state.active,pool=[...state.pools[index].values()];if(state.connecting||state.collecting)return toast('30초 수집이 끝난 뒤 뽑아주세요.');if(!pool.length)return toast('수집된 후보가 없습니다.');if(reroll&&!state.results[index])return toast('먼저 뽑기를 해주세요.');if(!reroll&&state.results[index])return toast('리롤 버튼을 사용해 주세요.');const winner=random(pool),reel=Array.from({length:38},()=>random(pool));reel.push(winner);state.rolling=true;$('reelTrack').replaceChildren(...reel.map(x=>{const d=document.createElement('div');d.className='reel-item';d.append(document.createTextNode(x.text));const n=document.createElement('small');n.textContent=x.name;d.append(n);return d}));render(false);const started=performance.now(),duration=4200;function frame(now){const t=Math.min(1,(now-started)/duration),p=1-Math.pow(1-t,3),h=$('reelTrack').firstElementChild.offsetHeight;$('reelTrack').style.transform=`translateY(${-p*(reel.length-1)*h}px)`;if(t<1)reelFrame=requestAnimationFrame(frame)}reelFrame=requestAnimationFrame(frame);drawTimer=setTimeout(()=>{state.results[index]=winner;state.rolling=false;render()},duration)}
function render(resetReel=true){const pool=[...state.pools[state.active].values()],result=state.results[state.active],done=state.results.filter(Boolean).length,busy=state.connecting||state.collecting||state.rolling;$('round').textContent='ROUND '+String(state.round).padStart(2,'0');$('streamerName').textContent=state.streamerName?state.streamerName+' 방송':'방송 연결 대기';$('progress').textContent=done+' / 5 확정';$('count').textContent=pool.length;$('status').textContent=state.status;$('collectState').textContent=state.connecting?'연결 중':state.collecting?'수집 중':'대기';$('collect').disabled=busy;$('collect').textContent=state.connecting?'SOOP 연결 중…':state.collecting?'채팅 수집 중':'30초 자동 수집';$('draw').disabled=busy||!pool.length||!!result;$('reroll').disabled=busy||!pool.length||!result;$('next').disabled=busy||done===5;$('clear').disabled=busy||isOverlay;$('demo').disabled=busy||isOverlay;$('reelLabel').textContent=fields[state.active]+' · '+(state.rolling?'룰렛 추첨':result?'선택된 운명':'채팅 룰렛');if(resetReel&&!state.rolling){$('reelTrack').style.transform='';$('reelTrack').innerHTML='';const d=document.createElement('div');d.className='reel-item';d.textContent=result?.text||(state.connecting?'SOOP 채팅방 연결 중…':state.collecting?'채팅을 모으고 있어요':'채팅을 수집해 주세요');$('reelTrack').append(d)}$('cards').replaceChildren(...fields.map((f,i)=>{const b=document.createElement('button'),r=state.results[i];b.className='card '+(i===state.active?'active ':'')+(r?'done':'');b.disabled=busy||isOverlay;b.onclick=()=>{state.active=i;render()};b.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><b>${f}</b>`;const v=document.createElement('div');v.className='value '+(!r?'pending':'');v.textContent=r?.text||(i===state.active?'채팅 수집을 시작해 주세요':'아직 정해지지 않았어요');if(r){const n=document.createElement('small');n.textContent=r.name+' 님';v.append(n)}b.append(v,document.createTextNode(r?'✓':i===state.active?'↗':'—'));return b}));$('candidates').replaceChildren(...(pool.length?pool.slice().reverse().map(x=>{const row=document.createElement('div');row.className='candidate';const d=document.createElement('div'),n=document.createElement('b'),p=document.createElement('p'),del=document.createElement('button');n.textContent=x.name;p.textContent=x.text;del.textContent='×';del.disabled=busy||isOverlay;del.onclick=()=>{state.pools[state.active].delete(x.id);render()};d.append(n,p);row.append(d,del);return row}):[Object.assign(document.createElement('p'),{textContent:state.connecting?'SOOP 채팅방에 연결하고 있습니다.':state.collecting?'채팅을 기다리고 있습니다.':'자동 수집을 시작해 주세요.'})]));tick();publish()}
function tick(){const left=Math.max(0,Math.ceil((state.until-Date.now())/1000));$('timer').textContent=state.connecting?'SOOP 연결 중…':state.collecting?left+'초 남음':state.rolling?'운명을 고르는 중…':'30초 수집 → 뽑기'}
$('collect').onclick=startCollection;$('draw').onclick=()=>draw(false);$('reroll').onclick=()=>draw(true);$('next').onclick=()=>{const n=state.results.findIndex((r,i)=>!r&&i>state.active);state.active=n<0?state.results.findIndex(r=>!r):n;render()};$('resetAll').onclick=()=>reset(true);$('clear').onclick=()=>{state.pools[state.active].clear();state.results[state.active]=null;render()};$('demo').onclick=()=>{reset(true);sample.forEach((list,i)=>list.forEach((text,j)=>state.pools[i].set('demo-'+i+'-'+j,{id:'demo-'+i+'-'+j,name:'테스트 '+(j+1),text})));state.status='테스트 후보를 넣었습니다.';render()};syncChannel&&(syncChannel.onmessage=event=>applySnapshot(event.data));addEventListener('storage',event=>{if(event.key===syncKey&&event.newValue)applySnapshot(event.newValue)});if(isOverlay){const saved=localStorage.getItem(syncKey);if(saved)applySnapshot(saved)}setInterval(tick,100);render();
