export const config={maxDuration:10};
function cleanConditions(value){if(!Array.isArray(value)||value.length<1||value.length>30)throw Error('완성된 환생 조건이 필요합니다.');return value.map(item=>({label:String(item?.label||'').trim().slice(0,30),value:String(item?.value||'').trim().slice(0,120)})).filter(item=>item.label&&item.value)}
function hash(text){let h=2166136261;for(const ch of text){h^=ch.codePointAt(0);h=Math.imul(h,16777619)}return h>>>0}
function random(seed){let n=seed||1;return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function pick(list,rng){return list[Math.floor(rng()*list.length)]}function get(map,label,fallback){return map.get(label)||fallback}

function createStory(conditions,seed){
 const rng=random(seed),map=new Map(conditions.map(item=>[item.label,item.value]));
 const country=get(map,'나라','이름 없는 먼 나라'),gender=get(map,'성별','누구의 기준에도 얽매이지 않는 존재'),body=get(map,'외모/신체','한 번 보면 오래 기억되는 인상');
 const family=get(map,'가정 환경','넉넉하지 않아도 서로의 편이 되어 주는 집'),wealth=get(map,'재산','내일을 장담하기 어려운 형편'),talent=get(map,'재능','결정적인 순간에 길을 찾아내는 능력');
 const personality=get(map,'성격','쉽게 꺾이지 않는 마음'),job=get(map,'직업','자기만의 방식으로 세상에 자리를 만드는 사람'),marriage=get(map,'결혼여부','사랑의 결말을 서두르지 않는 삶'),event=get(map,'특별 이벤트','아무도 예상하지 못한 거대한 사건');
 const basic=['나라','성별','외모/신체','가정 환경','재산','재능','성격','직업','결혼여부','특별 이벤트'],extras=conditions.filter(item=>!basic.includes(item.label));
 const title=pick([`《${country}에서 운명을 다시 쓰는 법》`,`《${job}, 이번 생의 주인공이 되다》`,`《두 번째 삶은 뜻대로 되지 않았다》`,`《운명이 건넨 열 가지 조건》`],rng);
 const birth=pick([`${country}의 하늘이 유난히 낮게 내려앉은 밤, ${family}에서 한 아이가 태어났다. 아이는 ${gender}으로 자랐고, ${body} 때문에 어디에 있든 사람들의 시선이 먼저 닿았다. 그러나 오래 기억되는 것은 겉모습보다 눈빛이었다. 아직 아무것도 가지지 못했으면서도, 세상에 묻고 싶은 것이 아주 많은 눈이었다.`,`${country}의 작은 동네에서 새로운 생이 시작됐다. ${family}은 화려한 미래를 약속해 주지는 못했지만, 넘어졌을 때 다시 일어나는 법만큼은 가르쳐 주었다. ${gender}인 주인공은 ${body}이라는 인상을 지녔고, 어린 시절부터 평범한 삶과는 조금 다른 방향으로 걸었다.`],rng);
 const youth=pick([`성장기는 순탄하지 않았다. 집안의 형편은 '${wealth}'에 가까웠고, 원하는 것을 얻으려면 남들보다 오래 기다리거나 직접 길을 만들어야 했다. 그 시간 속에서 '${personality}'이라는 성품이 단단해졌다. 때로는 그 성격 때문에 오해를 샀지만, 주인공은 타인의 기대에 자신을 끼워 맞추는 대신 선택의 결과를 감당하는 쪽을 택했다.`,`주인공에게 가장 먼저 현실을 가르친 것은 '${wealth}'이라는 사정이었다. 부족함은 부끄러움이 아니라 질문이 되었다. 무엇을 지켜야 하고 무엇을 포기할 것인가. 그 답을 찾는 동안 '${personality}'이라는 기질은 약점에서 신념으로 바뀌었다.`],rng);
 const discovery=pick([`전환점은 우연처럼 찾아왔다. 누구도 해결하지 못한 문제 앞에서 '${talent}'이 처음으로 빛난 것이다. 주인공은 재능이 선물인 동시에 책임이라는 사실을 깨달았다. 잘할 수 있다는 이유만으로 그 길을 선택한 것은 아니었다. 그 능력으로 어린 시절의 자신처럼 막막한 사람에게 출구를 보여 줄 수 있었기 때문이다.`,`학교와 거리, 몇 번의 실패를 지나며 주인공은 자신에게 '${talent}'이 있다는 사실을 알아냈다. 처음에는 대수롭지 않게 여겼지만, 그 힘이 누군가의 하루를 바꾸는 모습을 본 뒤 생각이 달라졌다. 재능은 자랑할 물건이 아니라 어디에 쓸지 결정해야 하는 칼날이었다.`],rng);
 const career=pick([`그 선택의 끝에서 주인공은 마침내 '${job}'의 길에 들어섰다. 시작은 초라했고 실수도 잦았다. 그럼에도 ${personality}인 사람답게 실패의 원인을 기록하고 다음 날 다시 문을 열었다. 시간이 흐르자 사람들은 결과보다 먼저 그 이름을 믿기 시작했다. 한때 발목을 잡던 '${wealth}'이라는 조건도 더는 삶의 크기를 정하지 못했다.`,`주인공이 택한 직업은 '${job}'이었다. 주변에서는 재능을 낭비한다고도, 너무 큰 꿈이라고도 말했다. 하지만 주인공은 '${talent}'을 자기 방식으로 갈고닦았고, 작은 성공에 머무르지 않았다. 그렇게 한 사람의 집념은 직업을 넘어 그 분야의 새로운 기준이 되었다.`],rng);
 const crisis=pick([`삶이 자리를 잡았다고 생각한 순간, '${event}'이 벌어졌다. 지금까지 쌓은 것을 지키려면 모른 척하는 편이 안전했다. 주인공은 두려워하면서도 사건의 한복판으로 걸어 들어갔다. ${talent}만으로는 부족했고, ${personality}이라는 성품만으로도 풀 수 없었다. 결국 사람들에게 도움을 청하고 함께 움직였을 때, 비로소 막혀 있던 길이 열렸다. 그날의 승리는 혼자 완성한 영웅담이 아니라 서로를 믿은 사람들이 만든 기적이었다.`,`가장 큰 시련은 '${event}'이었다. 사건은 명성과 재산, 소중한 관계까지 한꺼번에 시험했다. 도망칠 이유는 충분했지만 주인공은 자신이 처음 이 길을 택했던 이유를 기억했다. 가진 재능을 모두 쏟고도 마지막 한 걸음이 모자랐을 때, 오래전에 도왔던 사람들이 돌아와 그 곁을 채웠다. 선택은 돌고 돌아 운명이 되었다.`],rng);
 const relationship=pick([`그 격변을 지나며 사랑의 의미도 달라졌다. 기록에는 '${marriage}'이라고 남았지만, 주인공에게 중요한 것은 관계의 이름이 아니었다. 가장 어두운 순간에도 서로가 어떤 사람인지 잊지 않게 해 주는 것, 성공보다 평범한 저녁을 함께 기뻐하는 것이 사랑이었다.`,`주인공의 인연은 '${marriage}'이라는 모습으로 삶에 자리했다. 완벽해서 이어진 관계는 아니었다. 다투고 멀어졌다가도 진심을 숨기지 않는 법을 배웠기에 다시 같은 방향을 볼 수 있었다. 그 관계는 주인공이 홀로 버티는 사람에서 함께 살아가는 사람으로 변하는 마지막 계기가 되었다.`],rng);
 const extraText=extras.length?`\n\n운명에는 뒤늦게 드러난 조건도 있었다. ${extras.map(item=>`${item.label}은(는) '${item.value}'`).join(', ')}였다. 처음에는 사소해 보였던 이 조각들까지 예상 밖의 순간마다 선택에 영향을 주며, 누구도 대신 살아 줄 수 없는 고유한 생을 완성했다.`:'';
 const ending=pick([`세월이 흐른 뒤, 사람들은 주인공을 화려한 성공으로만 기억하지 않았다. ${country}에서 태어나 ${job}의 길을 걸으며 수많은 선택 앞에서 끝내 자기답게 답했던 사람. 생의 마지막 장에서 주인공은 처음 가졌던 것보다 훨씬 많은 것을 남겼다. 재산이 아니라 용기, 이름이 아니라 변화였다. 그리고 조용히 웃으며 말했다. “조건은 운명이 정했지만, 그 조건으로 어떤 사람이 될지는 내가 정했어.”`,`훗날 ${country}에는 주인공의 이야기가 오래 남았다. 사람들은 '${event}'을 전설처럼 말했지만, 정작 주인공이 가장 소중히 여긴 것은 그날 이후 이어진 평범한 날들이었다. ${job}으로서 해야 할 일을 하고, 사랑하는 사람의 안부를 묻고, 두려운 순간에도 한 걸음 내딛는 삶. 무작위로 주어진 조건들은 그렇게 하나의 단단한 인생이 되었다.`],rng);
 return [title,'― 프롤로그 ―',birth,'― 성장 ―',youth,discovery,'― 선택 ―',career,'― 운명의 전환점 ―',crisis,relationship+extraText,'― 에필로그 ―',ending].join('\n\n');
}
export default async function handler(req,res){if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'POST만 지원합니다.'})}try{const conditions=cleanConditions(req.body?.conditions);if(!conditions.length)throw Error('완성된 환생 조건이 필요합니다.');const seed=hash(JSON.stringify(conditions))+Date.now();res.setHeader('Cache-Control','no-store');return res.status(200).json({story:createStory(conditions,seed),mode:'free-story'})}catch(error){return res.status(400).json({error:error?.message||'환생 일대기를 만들지 못했습니다.'})}}
